Algoritmo "conversor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Entre com angulo e descubra o seno
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/05/2021
Var
// Seção de Declarações das variáveis 
  angulo, s:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  Escreval("Entre com o angulo")
  Leia(angulo)
  s <- Sen(GraupRad(angulo))
  Escreval("O seno de ", angulo, " é igual a ",s)
  

Fimalgoritmo