Algoritmo "expressoesLiterais"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Atribuir valores as variaveis
// Autor(a)    : Melquisedec Mendes
// Data atual  : 12/05/2021
Var
// Seção de Declarações das variáveis 
   a, b, c:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    a <- 2
    b <- a + 3
    c <- a + b
    
    Escreval(a)
    Escreval(b)
    Escreval(c)

Fimalgoritmo