Algoritmo "meuNome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Pergunta nome do usuário
// Autor(a)    : Melquisedec Mendes
// Data atual  : 10/05/2021
Var
// Seção de Declarações das variáveis 
 nome:caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Qual o seu nome?")
   Leia(nome)
   Escreval("Muito prazer ",nome)


Fimalgoritmo