Algoritmo "primeiroPrograma"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Imprimi mensagem na tela
// Autor(a)    : Melquisedec Mendes
// Data atual  : 08/05/2021
Var
// Seção de Declarações das variáveis 
 msg:caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  msg <- "Usando minha variávevel de texto"
  Escreval("Olá, revendo minha lógica de programação!!")
  Escreval(msg)

Fimalgoritmo