Algoritmo "quantosDolares"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Quantos dolares posso comprar
// Autor(a)    : Melquisedec Mendes
// Data atual  : 17/05/2021
Var
// Seção de Declarações das variáveis 
   reais, dolares: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval("Quantos reais você tem R$?")
   Leia(reais)
   dolares <- reais / 5.27
   Escreval("Você pode comprar ", dolares," dollares.")

Fimalgoritmo